# SparkTask Railway - Phase 1 Monorepo Configuration
# Fortune 500 Grade pnpm Workspace Structure
# Anti-Drift Governance: AUTHORIZED by governance document

packages:
  # Main web application
  - 'apps/web'

  # Shared UI package
  - 'packages/ui'

  # Configuration packages
  - 'configs/*'

  # Railway domain packages (Future Phase 2)
  - 'packages/railway-*'

  # Testing utilities
  - 'packages/test-utils'

# Performance optimizations
packageExtensions:
  '@tanstack/react-query':
    peerDependencies:
      react: '*'
      react-dom: '*'

  '@radix-ui/react-*':
    peerDependencies:
      react: '*'
      react-dom: '*'

# Shared dependencies hoisting
shamefullyHoist: false
strictPeerDependencies: true
