// Shell components for Fortune 500 enterprise features
export { KPICards } from './KPICards'
export { RecentList } from './RecentList'
export { QuickSearch } from './QuickSearch'

// Placeholder exports for other shell components
export const OrgSettings = () => 'Organization Settings - Coming Soon'
export const SecurityRBAC = () => 'Security RBAC - Coming Soon'
export const RLSPanel = () => 'RLS Panel - Coming Soon'
export const Backups = () => 'Backups - Coming Soon'
export const LinkedOrgs = () => 'Linked Organizations - Coming Soon'
export const CaptureInput = () => 'Capture Input - Coming Soon'
export const TriageList = () => 'Triage List - Coming Soon'
export const AIHintBar = () => 'AI Hint Bar - Coming Soon'
export const QuickAssign = () => 'Quick Assign - Coming Soon'
export const Agenda = () => 'Agenda - Coming Soon'
export const MiniMonth = () => 'Mini Month - Coming Soon'
export const ICSImport = () => 'ICS Import - Coming Soon'
export const FileBrowser = () => 'File Browser - Coming Soon'
export const AttachmentPanel = () => 'Attachment Panel - Coming Soon'
export const StorageBadge = () => 'Storage Badge - Coming Soon'
export const ApprovalDrawer = () => 'Approval Drawer - Coming Soon'
export const RequestForm = () => 'Request Form - Coming Soon'
export const AuditTimeline = () => 'Audit Timeline - Coming Soon'
export const AuditTable = () => 'Audit Table - Coming Soon'
export const FilterBar = () => 'Filter Bar - Coming Soon'
export const ExportButton = () => 'Export Button - Coming Soon'
export const StatusBanner = () => 'Status Banner - Coming Soon'
export const ConflictCenter = () => 'Conflict Center - Coming Soon'
export const SyncControls = () => 'Sync Controls - Coming Soon'
export const WelcomeWizard = () => 'Welcome Wizard - Coming Soon'
export const DemoLauncher = () => 'Demo Launcher - Coming Soon'
export const FeedbackForm = () => 'Feedback Form - Coming Soon'
export const DocsLink = () => 'Docs Link - Coming Soon'