// Core Railway Components - Fortune 500 PMBOK Implementation
export { RailMap } from './RailMap'
export { StationTabs } from './StationTabs'
export { BaseStation } from './BaseStation'
export { CharterWizard } from './CharterWizard'
export { TemplatePicker } from './TemplatePicker'
export { ScopeCard } from './ScopeCard'

// Placeholder Railway Components
export const BudgetForm = () => 'Budget Form - PMBOK Planning Phase'
export const ThresholdAlerts = () => 'Threshold Alerts - Coming Soon'
export const VarianceBadge = () => 'Variance Badge - Coming Soon'
export const Milestones = () => 'Milestones - PMBOK Schedule Management'
export const GanttLite = () => 'Gantt Lite - Coming Soon'
export const DependencyList = () => 'Dependency List - Coming Soon'
export const RiskList = () => 'Risk List - ISO 31000:2018'
export const HeatmapLite = () => 'Risk Heatmap - Coming Soon'
export const MitigationDrawer = () => 'Mitigation Drawer - Coming Soon'
export const TaskBoard = () => 'Task Board - Kanban Implementation'
export const Column = () => 'Column - Coming Soon'
export const Card = () => 'Card - Coming Soon'
export const WIPBadge = () => 'WIP Badge - Lean Manufacturing'
export const HandoverWizard = () => 'Handover Wizard - PMBOK Closing'
export const CompletionChecklist = () => 'Completion Checklist - Coming Soon'
export const KPIScorecard = () => 'KPI Scorecard - Balanced Scorecard'
export const LessonsPanel = () => 'Lessons Panel - Coming Soon'
export const ActionItems = () => 'Action Items - Coming Soon'