# E2E Testing with Enhanced Playwright Configuration
# Utilizes mobile testing, enhanced reporting, and failure analysis

name: E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Enterprise E2E tests
        run: npm run e2e:critical
        env:
          CI: true

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            test-results/
            playwright-report/
          retention-days: 7

      - name: Upload JUnit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: test-results/playwright-results.xml
          retention-days: 30

      - name: Comment PR with test results
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🧪 E2E Test Results
              
              ❌ Some E2E tests failed. Please check the uploaded artifacts for:
              - 📹 Video recordings of failed tests
              - 📸 Screenshots at failure points  
              - 🔍 Detailed traces for debugging
              
              **Mobile Testing**: Tests ran on both desktop and mobile viewports
              **Browsers Tested**: Chromium, Firefox, WebKit, Mobile Chrome, Mobile Safari
              
              [View full report in Actions artifacts](${context.payload.repository.html_url}/actions/runs/${context.runId})`
            })

  # Separate job for lighthouse/performance testing on mobile
  lighthouse-mobile:
    name: Mobile Performance
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start development server
        run: npm run dev &

      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Run Lighthouse on mobile
        run: |
          npm install -g @lhci/cli
          lhci autorun --config.ci.assert.assertions.speed-index=8000 \
                       --config.ci.assert.assertions.first-contentful-paint=4000 \
                       --config.ci.collect.settings.emulatedFormFactor=mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
