name: "SSOT Verify"

on:
  push:
    paths:
      - 'docs/SSOT.md'
      - 'SHORT_PROMPT.md'
  pull_request:
    paths:
      - 'docs/SSOT.md'
      - 'SHORT_PROMPT.md'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Validate SSOT files
        run: node ./tools/validate-ssot.js
